# Generated by Django 5.1 on 2024-08-24 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TerraformState",
            fields=[
                ("state_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("state_data", models.JSONField()),
                ("lock_id", models.CharField(max_length=255, null=True)),
                ("locked_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "django_terraform_http_backend_terraform_states",
            },
        ),
        migrations.CreateModel(
            name="HistoricalTerraformState",
            fields=[
                ("state_id", models.CharField(db_index=True, max_length=255)),
                ("state_data", models.JSONField()),
                ("lock_id", models.CharField(max_length=255, null=True)),
                ("locked_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical terraform state",
                "verbose_name_plural": "historical terraform states",
                "db_table": "django_terraform_http_backend_historical_terraform_states",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
